# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy project files to the container
COPY . .

# Upgrade pip and install project dependencies
RUN pip install --upgrade pip \
    && pip install mcp[cli]>=1.6.0 python-dotenv requests selenium

# Expose any necessary ports (if needed, not required for stdio transport)

# Set the entrypoint to run the MCP server
CMD ["python", "server.py"]
